### ISSUE TITLE
Renaming the repo

### ISSUE THREAD

**Issue by surbhigoel77** [DataWaveProject/newCAM_emulation#13]
Going through the `README.md` suggests that the name of the repository can be changed to a more intuitive one.

Links with #2

**Comment by jatkinson1000** [comment]
Perhaps "CAM Gravity Wave PyTorch Emulator"?

With details about how it forms a training pipeline on the comments.

**Comment by yqsun91** [comment]
I agree with Jack.  or just "CAM Gravity Wave Emulator"

**Comment by omarjamil** [comment]
Renamed.
