### ISSUE TITLE
Update project README.md

### ISSUE THREAD

**Issue by surbhigoel77** [DataWaveProject/newCAM_emulation#2]
We have a README available, but needs improvement.

- [x] Overview of the repo
- [x] Dataset Description
- [x] Installation Instructions
- [x] Instructions on how to run the model
- [x] Architecture of the ML model
- [ ] `CONTRIBUTING.md` file for future contributions
- [x] Reference to the Licence  
- [x] Add dependencies and linting tools to README (with versions if applicable)

**Comment by jatkinson1000** [comment]
A good example we can work from here is the [GZ project](https://github.com/m2lines/gz21_ocean_momentum) and [pyrealm](https://github.com/ImperialCollegeLondon/pyrealm).

There is a paper about this that contains key information which Qiang/Pedram can link here.

**Comment by jatkinson1000** [comment]
@yqsun91 @phz-fluids is this the paper you were referring to: https://arxiv.org/pdf/2311.17078.pdf

Is there an in-print version we can find with a DOI?

**Comment by yqsun91** [comment]
@jatkinson1000  Yes. that's the arxiv version.
The same is paper is also under minor revision at JAMES.  We will let you know once it is in press.

**Comment by jatkinson1000** [comment]
As discussed there should be some note about where the data is available, even if not publicly (e.g. on `glade/` with contact details), or a brief of how it can be reproduced by running CAM.
