### ISSUE TITLE
Add numpy-style docstrings to code

### ISSUE THREAD

**Issue by jatkinson1000** [DataWaveProject/newCAM_emulation#6]
Links #19  

The code is currently lacking docstrings, making its understanding difficult.

These should be added (perhaps once it is in a better refactored state see #5).

I suggest using the numpy format.

**Comment by omarjamil** [comment]
@surbhigoel77 can this be closed?

**Comment by surbhigoel77** [comment]
> @surbhigoel77 can this be closed?

I think so @omarjamil. Our in-progress work on the python code contains only numpy-style doctstrings now.

**Comment by surbhigoel77** [comment]
Numpy-style docstrings added to the latest version of work.
